"""Document, citation, and field-level assessment APIs."""

from mellea_lrc.assessment.citation import assess_found_citation
from mellea_lrc.assessment.context import (
    DocumentTextWindow,
    find_text_span_near_full_span,
    get_extended_span_text,
)
from mellea_lrc.assessment.document import (
    MelleaCallContext,
    initialize_assessment,
    run_assessment,
    run_assessment_async,
)
from mellea_lrc.assessment.fields.case_name import (
    ReextractionStatus,
    assess_case_name_exact_match,
    assess_case_name_with_mellea,
    build_extracted_case_name,
    reextract_case_name,
    validate_proposal,
)
from mellea_lrc.assessment.fields.year import assess_year_exact_match
from mellea_lrc.assessment.types import (
    AssessmentMetadata,
    AssessmentSkipReason,
    AssessmentStatus,
    AssessedCitationAssessment,
    AssessedDocument,
    CaseNameAssessment,
    CaseNameAssessmentRun,
    CaseNameAssessmentStatus,
    CaseNameFollowup,
    CaseNameFollowupStatus,
    CaseNameProposal,
    CaseNameReassessed,
    CaseNameReassessmentFailed,
    CaseNameReassessmentNotRequired,
    CaseNameReextractionFailed,
    ChatTurn,
    CitationAssessment,
    CitationAssessmentResult,
    FailedCitationAssessment,
    ReextractedCaseName,
    SkippedCitationAssessment,
    WaitingCitationAssessment,
    YearAssessment,
    YearAssessmentStatus,
)

__all__ = [
    "AssessedCitationAssessment",
    "AssessedDocument",
    "AssessmentMetadata",
    "AssessmentSkipReason",
    "AssessmentStatus",
    "CaseNameAssessment",
    "CaseNameAssessmentRun",
    "CaseNameAssessmentStatus",
    "CaseNameFollowup",
    "CaseNameFollowupStatus",
    "CaseNameProposal",
    "CaseNameReassessed",
    "CaseNameReassessmentFailed",
    "CaseNameReassessmentNotRequired",
    "CaseNameReextractionFailed",
    "ChatTurn",
    "CitationAssessment",
    "CitationAssessmentResult",
    "DocumentTextWindow",
    "FailedCitationAssessment",
    "MelleaCallContext",
    "ReextractedCaseName",
    "ReextractionStatus",
    "SkippedCitationAssessment",
    "WaitingCitationAssessment",
    "YearAssessment",
    "YearAssessmentStatus",
    "assess_case_name_exact_match",
    "assess_case_name_with_mellea",
    "assess_found_citation",
    "assess_year_exact_match",
    "build_extracted_case_name",
    "find_text_span_near_full_span",
    "get_extended_span_text",
    "initialize_assessment",
    "reextract_case_name",
    "run_assessment",
    "run_assessment_async",
    "validate_proposal",
]
