"""Mellea-assisted citation assessment helpers."""

from mellea_lrc.assessment.citation import (
    CitationAssessmentBundle,
    assess_found_citation,
    first_cluster_case_name,
    first_cluster_year,
)
from mellea_lrc.assessment.deterministic import (
    assess_case_name_exact_match,
    assess_year_exact_match,
    build_extracted_case_name,
    find_text_span_near_full_span,
    get_extended_span_text,
)
from mellea_lrc.assessment.pipeline import (
    MelleaCallContext,
    initialize_assessment,
    run_assessment,
    run_assessment_async,
)
from mellea_lrc.assessment.llm import (
    ReextractionStatus,
    assess_case_name_with_mellea,
    reextract_case_name,
    validate_proposal,
)
from mellea_lrc.assessment.types import (
    AssessmentSkipReason,
    AssessmentStatus,
    AssessedCitationAssessment,
    AssessedDocument,
    CaseNameAssessment,
    CaseNameAssessmentRun,
    CaseNameAssessmentStatus,
    CitationAssessment,
    CitationAssessmentResult,
    FailedCitationAssessment,
    ModifiedExtractedCitation,
    ModifiedExtractedCitationProposal,
    SkippedCitationAssessment,
    WaitingCitationAssessment,
    YearAssessment,
    YearAssessmentStatus,
)

__all__ = [
    "AssessedCitationAssessment",
    "AssessedDocument",
    "AssessmentSkipReason",
    "AssessmentStatus",
    "CaseNameAssessment",
    "CaseNameAssessmentRun",
    "CaseNameAssessmentStatus",
    "CitationAssessment",
    "CitationAssessmentBundle",
    "CitationAssessmentResult",
    "FailedCitationAssessment",
    "MelleaCallContext",
    "ModifiedExtractedCitation",
    "ModifiedExtractedCitationProposal",
    "ReextractionStatus",
    "SkippedCitationAssessment",
    "WaitingCitationAssessment",
    "YearAssessment",
    "YearAssessmentStatus",
    "assess_case_name_exact_match",
    "assess_case_name_with_mellea",
    "assess_found_citation",
    "assess_year_exact_match",
    "build_extracted_case_name",
    "find_text_span_near_full_span",
    "first_cluster_case_name",
    "first_cluster_year",
    "get_extended_span_text",
    "initialize_assessment",
    "reextract_case_name",
    "run_assessment",
    "run_assessment_async",
    "validate_proposal",
]
