"""Post-extraction citation validation."""

from mellea_lrc.validation.pipeline import initialize_validation, validate_document
from mellea_lrc.validation.types import (
    CandidateEvaluationNode,
    CandidateEvaluationOutcome,
    CandidateEvaluationSource,
    CandidateSelectionNode,
    CandidateSelectionOutcome,
    CitationValidation,
    CourtCheckNode,
    DocketCourtRetrievalNode,
    DocketCourtRetrievalOutcome,
    ExactCaseNameCheckNode,
    ExactLocatorLookupNode,
    FieldCheckOutcome,
    LocatorLookupOutcome,
    MelleaCaseNameCheckNode,
    MelleaCaseNameCheckOutcome,
    MelleaCaseNameQueryPreparationNode,
    MelleaCaseNameQueryPreparationOutcome,
    MelleaCaseNameReextractionNode,
    MelleaCaseNameReextractionOutcome,
    MelleaReextractedCaseNameCheckNode,
    OpinionSearchNode,
    OpinionSearchOutcome,
    RecapSearchNode,
    RecapSearchOutcome,
    ValidatedDocument,
    ValidationNode,
    ValidationNodeStatus,
    YearCheckNode,
)

__all__ = [
    "CandidateEvaluationNode",
    "CandidateEvaluationOutcome",
    "CandidateEvaluationSource",
    "CandidateSelectionNode",
    "CandidateSelectionOutcome",
    "CitationValidation",
    "CourtCheckNode",
    "DocketCourtRetrievalNode",
    "DocketCourtRetrievalOutcome",
    "ExactCaseNameCheckNode",
    "ExactLocatorLookupNode",
    "FieldCheckOutcome",
    "LocatorLookupOutcome",
    "MelleaCaseNameCheckNode",
    "MelleaCaseNameCheckOutcome",
    "MelleaCaseNameQueryPreparationNode",
    "MelleaCaseNameQueryPreparationOutcome",
    "MelleaCaseNameReextractionNode",
    "MelleaCaseNameReextractionOutcome",
    "MelleaReextractedCaseNameCheckNode",
    "OpinionSearchNode",
    "OpinionSearchOutcome",
    "RecapSearchNode",
    "RecapSearchOutcome",
    "ValidatedDocument",
    "ValidationNode",
    "ValidationNodeStatus",
    "YearCheckNode",
    "initialize_validation",
    "validate_document",
]
