"""Citation retrieval from external legal-data services."""

from mellea_lrc.courtlistener.remote import CourtListenerAccessClient, CourtListenerAccessConfig
from mellea_lrc.retrieval.pipeline import run_retrieval, run_retrieval_async
from mellea_lrc.retrieval.types import (
    AmbiguousCitationRetrieval,
    CaseNamePreparationStatus,
    CaseNameSearchCorpus,
    CaseNameSearchPreparation,
    CaseNameSearchProbe,
    CaseNameSearchStatus,
    CaseNameSearchTrace,
    CitationRetrieval,
    CourtListenerRequestTrace,
    CourtResolutionSource,
    CourtResolutionTrace,
    FoundCitationRetrieval,
    InvalidCitationRetrieval,
    LookupFailedCitationRetrieval,
    NotFoundCitationRetrieval,
    RetrievedCandidate,
    RetrievedDocument,
    RetrievalClientMode,
    RetrievalMetadata,
    RetrievalStatus,
    SkippedCitationRetrieval,
    ThrottledCitationRetrieval,
)

__all__ = [
    "AmbiguousCitationRetrieval",
    "CaseNamePreparationStatus",
    "CaseNameSearchCorpus",
    "CaseNameSearchPreparation",
    "CaseNameSearchProbe",
    "CaseNameSearchStatus",
    "CaseNameSearchTrace",
    "CitationRetrieval",
    "CourtListenerAccessClient",
    "CourtListenerAccessConfig",
    "CourtListenerRequestTrace",
    "CourtResolutionSource",
    "CourtResolutionTrace",
    "FoundCitationRetrieval",
    "InvalidCitationRetrieval",
    "LookupFailedCitationRetrieval",
    "NotFoundCitationRetrieval",
    "RetrievalClientMode",
    "RetrievalMetadata",
    "RetrievalStatus",
    "RetrievedCandidate",
    "RetrievedDocument",
    "SkippedCitationRetrieval",
    "ThrottledCitationRetrieval",
    "run_retrieval",
    "run_retrieval_async",
]
